#ifndef ERROR_H
# define ERROR_H


# define END "THE END\n"
# define PAR "THERE ARE NOT ARGUMENTS\n"
# define MALLOC_FAIL "FAILED TO ALLOCATE MEMORY\n"
# define BAD_PAR "BAD PARAMETER\n"
# define PHILOERR "THE PHILOSOPHER CANNOT EAT WITH A FORK\n"

#endif
