#ifndef ERROR_H
# define ERROR_H


# define END "THE END\n"
# define PAR "WRONG NUMBERS OF PARAMETERS\n"
# define MALLOC_FAIL "FAILED TO ALLOCATE MEMORY\n"
# define BAD_PAR "BAD PARAMETER\n"
# define PHILOERR "TOO MANY PHILOSOPHERS\n"

#endif
