#ifndef ERROR_H
# define ERROR_H


# define END "THE END\n"
# define PAR "THERE ARE NOT ARGUMENTS\n"
# define THREAD_FAIL "FAILED TO CREATE THREAD\n"
# define BAD_PAR "BAD PARAMETER\n"
# define PHILOERR "TOO MANY PHILOSOPHERS\n"

#endif
